services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-gmontinny}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-Gmontinny2026}
      - POSTGRES_DB=${POSTGRES_DB:-db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - ecommerce_network

  app:
    build: .
    container_name: ecommerce_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge

volumes:
  postgres_data:
